import '@/styles/globals.css';
import { monsterrrat } from "@/utils/fonts";
import { Metadata } from 'next';


export const metadata: Metadata = {
  metadataBase: null,
  title: { default: '', template: '%s | Would You Rather'},
  description: 'Generated by create next app',
  applicationName: 'Would You Rather',
  authors: { name: 'Yarne Savaete', url: 'https://yarnesavaete.com' },
  generator: 'Next.js',
  keywords: ['Would You Rather', 'Minigame', 'choose', 'random', 'game'],
  viewport: { width: "device-width", initialScale: 1 },
  creator: 'Yarne Savaete',
  publisher: 'Yarne Savaete',
  robots: { index: true, follow: true },
  appleWebApp: { capable: true, title: "Would You Rather", statusBarStyle: "default" },
  formatDetection: { telephone: false },
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={monsterrrat.className}>
        { children }
      </body>
    </html>
  )
}
